run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0
  funlen:
    lines: 40
    statements: 25
    ignore-comments: true
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 100
    tab-width: 4
  nestif:
    min-complexity: 4
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: early-return
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
      - name: var-declaration
      - name: var-naming
  staticcheck:
    checks:
      - all
